# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Sun Sep  4 19:20:37 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(715, 815)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("mariusz/logo2.png"))
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.model = QtWidgets.QLabel(self.centralwidget)
        self.model.setObjectName("model")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.model)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setStyleSheet("QGroupBox\n"
"{\n"
"padding: 5px;\n"
"border: 1px solid rgb(136, 136, 136);\n"
"border-radius: 4px;\n"
"margin-top: 8px;\n"
"}\n"
"QGroupBox::title {\n"
"top: -8px;\n"
"left: 10px;\n"
"}\n"
"")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setContentsMargins(-1, 5, -1, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_3.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_3.addWidget(self.radioButton_6)
        spacerItem1 = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_10.setObjectName("comboBox_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_10)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_11.setObjectName("comboBox_11")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_11)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(-1, 1, -1, -1)
        self.formLayout_3.setHorizontalSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.uchwyty = QtWidgets.QLabel(self.centralwidget)
        self.uchwyty.setObjectName("uchwyty")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.uchwyty)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.zasilanie = QtWidgets.QLabel(self.centralwidget)
        self.zasilanie.setObjectName("zasilanie")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.zasilanie)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.kontrola = QtWidgets.QLabel(self.centralwidget)
        self.kontrola.setObjectName("kontrola")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.kontrola)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.ochrona = QtWidgets.QLabel(self.centralwidget)
        self.ochrona.setObjectName("ochrona")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ochrona)
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.ilosc_1 = QtWidgets.QLabel(self.centralwidget)
        self.ilosc_1.setObjectName("ilosc_1")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.ilosc_1)
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.typ_1 = QtWidgets.QLabel(self.centralwidget)
        self.typ_1.setObjectName("typ_1")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.typ_1)
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.ilosc_2 = QtWidgets.QLabel(self.centralwidget)
        self.ilosc_2.setObjectName("ilosc_2")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.ilosc_2)
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.typ_2 = QtWidgets.QLabel(self.centralwidget)
        self.typ_2.setObjectName("typ_2")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.typ_2)
        self.comboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.comboBox_9)
        self.index_short = QtWidgets.QLabel(self.centralwidget)
        self.index_short.setObjectName("index_short")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.index_short)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.index_long = QtWidgets.QLabel(self.centralwidget)
        self.index_long.setObjectName("index_long")
        self.formLayout_3.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.index_long)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_3.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.comboBox_12 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_12.setObjectName("comboBox_12")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 441, 31))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.frame)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.verticalLayout.addLayout(self.formLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.model.setText(_translate("MainWindow", "Model listwy:"))
        self.groupBox.setTitle(_translate("MainWindow", "Konfiguracja NPM - V"))
        self.radioButton.setText(_translate("MainWindow", "7V"))
        self.radioButton_2.setText(_translate("MainWindow", "8V"))
        self.radioButton_3.setText(_translate("MainWindow", "A"))
        self.radioButton_4.setText(_translate("MainWindow", "B"))
        self.radioButton_5.setText(_translate("MainWindow", "C"))
        self.radioButton_6.setText(_translate("MainWindow", "D"))
        self.label.setText(_translate("MainWindow", "Akcesoria dodatkowe:"))
        self.label_2.setText(_translate("MainWindow", "Typ czujników:"))
        self.uchwyty.setText(_translate("MainWindow", "Uchwyty:"))
        self.zasilanie.setText(_translate("MainWindow", "Zasilanie na wejściu:"))
        self.kontrola.setText(_translate("MainWindow", "Kontrola PDU:"))
        self.ochrona.setText(_translate("MainWindow", "Ochrona PDU:"))
        self.ilosc_1.setText(_translate("MainWindow", "Ilość gniazd I typu:"))
        self.typ_1.setText(_translate("MainWindow", "I typ gniazd:"))
        self.ilosc_2.setText(_translate("MainWindow", "Ilość gniazd II typu:"))
        self.typ_2.setText(_translate("MainWindow", "II typ gniazd: "))
        self.index_short.setText(_translate("MainWindow", "Index krótki:"))
        self.index_long.setText(_translate("MainWindow", "Index długi: "))
        self.pushButton.setText(_translate("MainWindow", "Prześlij dane do pliku"))
        self.label_3.setText(_translate("MainWindow", "Długość kabla"))
        self.label_4.setText(_translate("MainWindow", "Wpisz długość kabla: "))
        self.label_5.setText(_translate("MainWindow", "Dobrany kabel:"))

