# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Fri Sep  2 21:00:32 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1338, 580)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("mariusz/logo2.png"))
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.model = QtWidgets.QLabel(self.centralwidget)
        self.model.setObjectName("model")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.model)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.uchwyty = QtWidgets.QLabel(self.centralwidget)
        self.uchwyty.setObjectName("uchwyty")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.uchwyty)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.zasilanie = QtWidgets.QLabel(self.centralwidget)
        self.zasilanie.setObjectName("zasilanie")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.zasilanie)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.kontrola = QtWidgets.QLabel(self.centralwidget)
        self.kontrola.setObjectName("kontrola")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.kontrola)
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.ochrona = QtWidgets.QLabel(self.centralwidget)
        self.ochrona.setObjectName("ochrona")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.ochrona)
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.ilosc_1 = QtWidgets.QLabel(self.centralwidget)
        self.ilosc_1.setObjectName("ilosc_1")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ilosc_1)
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.typ_1 = QtWidgets.QLabel(self.centralwidget)
        self.typ_1.setObjectName("typ_1")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.typ_1)
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.ilosc_2 = QtWidgets.QLabel(self.centralwidget)
        self.ilosc_2.setObjectName("ilosc_2")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.ilosc_2)
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.typ_2 = QtWidgets.QLabel(self.centralwidget)
        self.typ_2.setObjectName("typ_2")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.typ_2)
        self.comboBox_9 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_9)
        self.index_short = QtWidgets.QLabel(self.centralwidget)
        self.index_short.setObjectName("index_short")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.index_short)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.index_long = QtWidgets.QLabel(self.centralwidget)
        self.index_long.setObjectName("index_long")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.index_long)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.pushButton)
        self.verticalLayout.addLayout(self.formLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.model.setText(_translate("MainWindow", "Model listwy:"))
        self.uchwyty.setText(_translate("MainWindow", "Uchwyty:"))
        self.zasilanie.setText(_translate("MainWindow", "Zasilanie na wejściu:"))
        self.kontrola.setText(_translate("MainWindow", "Kontrola PDU:"))
        self.ochrona.setText(_translate("MainWindow", "Ochrona PDU:"))
        self.ilosc_1.setText(_translate("MainWindow", "Ilość gniazd I typu:"))
        self.typ_1.setText(_translate("MainWindow", "I typ gniazd:"))
        self.ilosc_2.setText(_translate("MainWindow", "Ilość gniazd II typu:"))
        self.typ_2.setText(_translate("MainWindow", "II typ gniazd: "))
        self.index_short.setText(_translate("MainWindow", "Index krótki:"))
        self.index_long.setText(_translate("MainWindow", "Index długi: "))
        self.pushButton.setText(_translate("MainWindow", "Prześlij dane do pliku"))

